name: Build Deno Binary

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build Binary
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Compile Deno project
        run: deno compile --allow-read --allow-env --allow-net src/index.ts

      - name: Upload binary artifact
        uses: actions/upload-artifact@v3
        with:
          name: deno-binary
          path: main
